### ISSUE TITLE
[BUG] Navigating to another component version using Browser Extension does not always work for NPM

### ISSUE THREAD

**Issue by sini01** [sonatype-nexus-community/sonatype-platform-browser-extension#106]
**Describe the bug**
Accessing Another Component Version, from component main/default page (i.e. https://www.npmjs.com/package/lodash) while using Browser PlugIn (in this case Chrome PlugIn), doesn’t open the Selected Version Page as it would if another Component Version is accessed from a Specific Version page (i.e. https://www.npmjs.com/package/lodash/v/4.17.21)

**To Reproduce**
Attached Images 1 & 2
1. Open a Component Default page in Chrome browser (in this case latest v4.17.21)
2. Click on Sonatype Browser Extension PlugIn Icon to open it
3. Select Remediation tab (note - it will be Version tab rather than Remediation if component doesn’t have vulns)
4. Click on another Version (i.e. v4.17.19)
5. The browser won’t bring the Selected Version (4.17.19) but rather stays at the Default (4.17.21)

**Expected behavior**
As described in step 5 below - Attached Images 3 & 4
1. Open a Specific Component version page in Chrome browser (v4.17.21)
2. Click on Sonatype Browser Extension PlugIn Icon to open it
3. Select Remediation tab (note - it will be Version tab rather than Remediation if component doesn’t have vulnerabilities)
4. Click on another Version (i.e. v4.17.19)
5. The browser will display the Selected Version (4.17.19)

**Screenshots**
Images 1, 2, 3, 4
<img width="1207" alt="Image #1" src="https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/103262875/90ef6d0f-b15d-4226-a958-d1f39c074cca">

<img width="1210" alt="Image #2" src="https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/103262875/c62a5b88-e431-4121-b31c-db1b750fa3f2">

<img width="1205" alt="Image #3" src="https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/103262875/ba5b9e8d-0c0e-43c0-939b-a68a8a02710b">

<img width="1206" alt="Image #4" src="https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/103262875/1d091b7b-5cbc-44a9-94ee-6624c1481b9e">

**Desktop (please complete the following information):**
Environment:              Local Machine
Local Machine:           Apple M1 Max - MacOS, Sonoma 14.0
Browser:                     Chrome Version 118.0.5993.70 (Official Build) (arm64)
Browser Extension:   rel 2.13.1
IQ:                               rel 167
Produce License:       NXRM + FW for NXRM + FW for Artifactory (Test)

**Smartphone (please complete the following information):**
   N/A

**Additional context**
Edge Browser PlugIn and Lifecycle Licence version were out of scope for this validation

Scope/Impacted Ecosystems as validated
   Npm	https://www.npmjs.com/
   Pypi	https://www.nuget.org/
   NuGet	https://www.nuget.org/
   Maven	https://central.sonatype.com/

**Comment by madpah** [comment]
Confirmed that navigation to another version for NPM by selecting a version in the Browser Extension WHEN the current page is the root package with no version (i.e. https://www.npmjs.com/package/lodash vs https://www.npmjs.com/package/lodash/v/4.17.21) does not work in 2.13.1.

**Comment by madpah** [comment]
This issue is believed to expand to potentially other registries also - fix will be worked on.

FYI @sini01
