### ISSUE TITLE
FEAT: Show Popularity, Hygiene and Integrity Rating for Components

### ISSUE THREAD

**Issue by george-sntp** [sonatype-nexus-community/sonatype-platform-browser-extension#123]
Can we add Component Metadata as Popularity, Hygiene and Integrity Rating to the extension? 

This will help developers in their selections of best components in the central repositories. 

A nice place to display would be right under the component name in the **Info** tab.

**Comment by madpah** [comment]
Hey @george-sntp - thanks for the feature request.

These fields do appear in the API requests already made, but appear to always be returned as `null` values - we'll have to investigate further.

FYI @maurycupitt

**Comment by maurycupitt** [comment]
Popularity for each version is in the all versions list.

**Comment by madpah** [comment]
Agreed @maurycupitt.

@george-sntp - Popularity and Integrity Rating are already included where supported:

![Screenshot 2024-08-27 at 13 59 56](https://github.com/user-attachments/assets/2d5b1c5f-7887-4be0-92e2-135f5cea57a7)

![Screenshot 2024-08-27 at 14 00 09](https://github.com/user-attachments/assets/c2ed7ab8-0657-4003-b30e-5b52c3599170)
