### ISSUE TITLE
Google stating lack of support for the extension

### ISSUE THREAD

**Issue by george-sntp** [sonatype-nexus-community/sonatype-platform-browser-extension#124]
Please address this message we are getting from Google Extensions:

![Screenshot 2024-08-23 at 13 24 18](https://github.com/user-attachments/assets/da7582f2-a44b-45ee-93ee-782ac31d4071)

**Comment by madpah** [comment]
Can you share where exactly you are seeing this warning please @george-sntp ? Perhaps a more complete screenshot?

**Comment by george-sntp** [comment]
as soon as I hit "Manage Extensions", on the home page, the message is displayed
![Screenshot 2024-08-23 at 14 56 24](https://github.com/user-attachments/assets/0e356afc-eba8-46d0-ad3e-aaa646bce738)

**Comment by madpah** [comment]
Weirdly I do not get this behaviour @george-sntp...

**Comment by madpah** [comment]
Ahh - that is the OLD and now deprecated extension - not this extension @george-sntp - you can remove that old extension.

**Comment by george-sntp** [comment]
correct, I still had both...  removed, thank you!
