### ISSUE TITLE
Integrity Rating link is broken

### ISSUE THREAD

**Issue by george-sntp** [sonatype-nexus-community/sonatype-platform-browser-extension#132]
The Integrity Rating link is broken, pointing to a page that no longer exists: 

https://help.sonatype.com/fw/next-gen-firewall-features/protection-from-pending-and-suspicious-components

It should probably point to:

https://help.sonatype.com/en/release-integrity.html

![Screenshot 2024-09-03 at 12 50 32](https://github.com/user-attachments/assets/53639987-97be-4844-9a91-a2cc45bac857)

**Comment by madpah** [comment]
This was included in release `2.19.0` submitted to the various stores a few minutes ago @george-sntp!

**Comment by madpah** [comment]
See #123
