### ISSUE TITLE
bug: need to update extension version number where shown

### ISSUE THREAD

**Issue by maurycupitt** [sonatype-nexus-community/sonatype-platform-browser-extension#18]
**Describe the bug**
The version number of the extension is displayed in the nav bar of the options page as well as in the 

**Expected behavior**
Automate the version update on release if possible.

**Screenshots**
<img width="228" alt="image" src="https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/3226578/5998eec4-e63b-4242-8b5c-a0e2c8843582">

<img width="407" alt="image" src="https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/3226578/e6c85120-35d1-4b61-a822-3a9df41b108f">

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by madpah** [comment]
There are a few things to fix here I believe @maurycupitt:

1. We are not automatically committing the `package.json` back to Git during a release
2. `options.tsx` is reading the version from the `package.json` and instead should be reading from the Manifest via `chrome.runtime.getManifest()` or equivalent

**Comment by madpah** [comment]
Included in release 2.1.2
