### ISSUE TITLE
PyPi component not working

### ISSUE THREAD

**Issue by maurycupitt** [sonatype-nexus-community/sonatype-platform-browser-extension#27]
**Describe the bug**
Unable to get component details for pypi component https://pypi.org/project/shield34/

<img width="1396" alt="image" src="https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/3226578/7e5101ea-d9cb-4e32-a850-a34c30a5cd83">

**To Reproduce**
1. Go to https://pypi.org/project/shield34/
2. Open the extension

**Expected behavior**
Expect to see component information of component

**Desktop (please complete the following information):**
 - Browser Chrome

**Additional context**
Failed to load resource: the server responded with a status of 400 ()

**Comment by madpah** [comment]
The extension is calculating the correct PURL for the Component on this page: `pkg:pypi/shield34@1.0.408?extension=tar.gz` - however, Sonatype IQ Server does not appear to know about this component and returns:

`"matchState": "unknown",`

**Comment by madpah** [comment]
I believe this is because there is no `.tar.gz` component published for shield34@1.0.408 - see https://pypi.org/project/shield34/#files

We are currently hard-coding the extension to be `.tar.gz` as we assume every PyPi package has a source archive published.

FYI @maurycupitt

**Comment by madpah** [comment]
![Screenshot 2023-07-14 at 09 35 34](https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/10280392/89d87554-3d8e-4447-a884-90b09181073c)
