### ISSUE TITLE
Plugin Logo Disappears from pinned items upon Remediation

### ISSUE THREAD

**Issue by bryanwhyte** [sonatype-nexus-community/sonatype-platform-browser-extension#35]
When Plugin is installed & pinned to Chrome Browser the Lifecycle Logo is clearly visible in the tray when you open a new browser tab - for my computer it's BLUE on WHITE background.

If you select a version of OSS with vulnerabilities, the logo for LC turns to RED on WHITE background.

If you Select the Remediation Tab in the plugin and select a fix version - the page will switch to that version of the component and the Browser Plugin Lifecycle Logo will turn to WHITE on WHITE background.

**Comment by maurycupitt** [comment]
This was fixed when we updated the extension logo color to match the policy severity.
