### ISSUE TITLE
Add support for Korean locale

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/sonatype-platform-browser-extension#37]
**Is your feature request related to a problem? Please describe.**
No, this is a new feature. Add Korean language locale support.

**Describe the solution you'd like**
Have Korean language translation for Browser extension messages.

**Describe alternatives you've considered**
Just use English

**Additional context**
I have translation from Korean partner

**Comment by madpah** [comment]
Implemented by #37.
