### ISSUE TITLE
No response from extension when using https://conan.io/center/

### ISSUE THREAD

**Issue by shiftingleft** [sonatype-nexus-community/sonatype-platform-browser-extension#69]
**Describe the bug**
The extension appears unresponsive on this public registry despite listed support.

**To Reproduce**
Go to any library on the site.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 116.0.5845.96

**Comment by madpah** [comment]
@shiftingleft - thanks for the report. So we can triage - please can you provide a specific full example URL that is not working?

**Comment by shiftingleft** [comment]
@madpah sure - as an example: https://conan.io/center/recipes/proj?version=8.2.1 but for clarity, I don't get the expected response from the extension on any library it seems.

**Comment by madpah** [comment]
It appears `conan.io` has changed it HTML and URL formats recently, breaking our integration for this Open Source Registry.
